services:
  - type: web
    name: whatsapp-connector
    env: docker
    region: ohio
    plan: standard # You need at least the standard plan for this to work reliably
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    dockerCommand: node src/simple-whatsapp.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: whatsapp-auth
      mountPath: /app/auth_data
      sizeGB: 1 