services:
  - type: web
    name: whatsapp-connector
    env: docker
    region: ohio
    plan: standard # You need at least the standard plan for this to work reliably
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    dockerCommand: /app/monitor.sh & node src/simple-whatsapp.js
    autoDeploy: false # Disable auto-deploy to prevent issues during development
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=384
    scaling:
      minInstances: 1
      maxInstances: 1 # Prevent scaling to ensure state consistency
    disk:
      name: whatsapp-auth
      mountPath: /app/auth_data
      sizeGB: 1 